package my.vaadin.cm;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class EditLecturePanelDesign extends FormLayout {
	protected NativeSelect<java.lang.String> login;
	protected TextField dateTime;
	protected NativeSelect<java.lang.String> subject;
	protected Button cancel;
	protected Button save;

	public EditLecturePanelDesign() {
		Design.read(this);
	}
}
